name: Java
on: [push, pull_request, repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
defaults:
  run:
    shell: bash

jobs:
  java:
    name: Java
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      GEN: ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
    steps:
      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
        with:
          vcpkgGitCommitId: 84bab45d415d22042bd0b9081aea57f362da3f35
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: java
          max-size: 2G
      - name: Build Arrow Extension
        run: make release
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: test/java/pom.xml
      - name: Test Java
        run: mvn -B -f test/java/pom.xml test -Dduckdb.shell="$GITHUB_WORKSPACE/build/release/duckdb"
